version: '3'
services:
  app:
    build: .
    environment:
      - PORT=3000
      - NODE_ENV=dev
      - ENV_NAME=local
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
    - ./src:/opt/app/src
